/*
 * Differential check for
 * patches/0014-submcu-skip-idle-interrupt-scan.patch.
 *
 * SM_HandleInterrupt walks nine arms; eight require a bit in INT_REQUEST and
 * the ninth requires COLLISION bits 7:6 both set. The patch answers the
 * common nothing-pending case from those two bytes before the walk. So the
 * property to prove is: for every machine state, the patched handler leaves
 * the sub-MCU exactly where upstream's leaves it, makes the same outward
 * calls, and dispatches the same vector or none.
 *
 * The core's real submcu.cpp is linked twice: the patched one normally, and
 * upstream's with every global renamed Ref_* (the -D list is generated by
 * the runner from nm). Both are driven over (1) the guard's entire firing
 * domain exhaustively -- INT_REQUEST = 0 crossed with every collision byte,
 * every enable byte, every relevant control-bit combination, every cts and
 * both I states -- and (2) millions of unconstrained random states, with the
 * whole submcu_t compared after every call.
 *
 * The guard is restated behind BREAK_SCAN so the mutants can prove the test
 * can fail:
 *
 *   -DBREAK_SCAN=1  drops the collision test entirely
 *   -DBREAK_SCAN=2  || for &&: skips the scan whenever either half passes
 *   -DBREAK_SCAN=3  collision compared against the wrong value
 */
#include "submcu.h"
#include "mcu.h"
#include "diagnostics.h"

void SM_HandleInterrupt(submcu_t& sm);

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

/* Outward calls submcu.cpp can make; recorded so both copies must agree. */
struct StubCall { const char* what; uint64_t a, b; };
static std::vector<StubCall>& StubLog() { static std::vector<StubCall> log; return log; }
static void Note(const char* what, uint64_t a = 0, uint64_t b = 0)
{ StubLog().push_back({what, a, b}); }
static bool SameCalls(const std::vector<StubCall>& x, const std::vector<StubCall>& y)
{
    if (x.size() != y.size()) return false;
    for (size_t i = 0; i < x.size(); i++)
        if (strcmp(x[i].what, y[i].what) || x[i].a != y[i].a || x[i].b != y[i].b)
            return false;
    return true;
}

void Diag_Printf(Diag_Category, const char* format, ...) { Note("Diag_Printf", (uint64_t)(uintptr_t)format); }
uint8_t MCU_ReadP0(mcu_t&) { Note("MCU_ReadP0"); return 0x5a; }
uint8_t MCU_ReadP1(mcu_t&) { Note("MCU_ReadP1"); return 0xa5; }
void MCU_WriteP0(mcu_t&, uint8_t v) { Note("MCU_WriteP0", v); }
void MCU_WriteP1(mcu_t&, uint8_t v) { Note("MCU_WriteP1", v); }
void MCU_GA_SetGAInt(mcu_t&, uint8_t i, bool v) { Note("MCU_GA_SetGAInt", i, v); }

void Ref_SM_HandleInterrupt(submcu_t& sm);

namespace {

enum {
    DEV_UART1_CTRL = 0x06, DEV_UART2_CTRL = 0x0a, DEV_UART3_CTRL = 0x0e,
    DEV_COLLISION = 0x1a, DEV_INT_ENABLE = 0x1b, DEV_INT_REQUEST = 0x1c,
    DEV_TIMER_CTRL = 0x1f,
};

/* The patch's guard, restated ahead of the upstream handler so a broken
 * guard can be checked against the same reference. With BREAK_SCAN unset it
 * is a literal copy of what the patch adds. */
void GuardUnderTest(submcu_t& sm)
{
    if (!(sm.sr & 4 /* SM_STATUS_I */))
    {
#if BREAK_SCAN == 1
        if (sm.device_mode[DEV_INT_REQUEST] == 0)
            return;
#elif BREAK_SCAN == 2
        if (sm.device_mode[DEV_INT_REQUEST] == 0
            || (sm.device_mode[DEV_COLLISION] & 0xc0) != 0xc0)
            return;
#elif BREAK_SCAN == 3
        if (sm.device_mode[DEV_INT_REQUEST] == 0
            && (sm.device_mode[DEV_COLLISION] & 0xc0) != 0x40)
            return;
#else
        if (sm.device_mode[DEV_INT_REQUEST] == 0
            && (sm.device_mode[DEV_COLLISION] & 0xc0) != 0xc0)
            return;
#endif
    }
    Ref_SM_HandleInterrupt(sm);
}

uint32_t Rand(uint32_t& s) { s ^= s << 13; s ^= s >> 17; s ^= s << 5; return s; }

int failures = 0;

void Check(submcu_t& a, submcu_t& b, submcu_t& c,
           const std::vector<StubCall>& la, const std::vector<StubCall>& lb,
           const std::vector<StubCall>& lc, const char* which)
{
    if (memcmp(&a, &b, sizeof(submcu_t)) != 0 || !SameCalls(la, lb)
        || memcmp(&c, &b, sizeof(submcu_t)) != 0 || !SameCalls(lc, lb))
    {
        if (failures < 10)
            printf("MISMATCH %s req=%02x coll=%02x en=%02x sr=%02x\n", which,
                   b.device_mode[DEV_INT_REQUEST], b.device_mode[DEV_COLLISION],
                   b.device_mode[DEV_INT_ENABLE], b.sr);
        failures++;
    }
}

} // namespace

int main()
{
    static submcu_t pat{}, ref{}, tst{};
    uint32_t seed = 0x5eed1234;

    /* Vector table and stack targets: identical random fill in all copies. */
    static uint8_t rom_fill[4096], ram_fill[128], shared_fill[192];
    for (auto& x : rom_fill) x = (uint8_t)Rand(seed);
    for (auto& x : ram_fill) x = (uint8_t)Rand(seed);
    for (auto& x : shared_fill) x = (uint8_t)Rand(seed);

    auto reset = [&](submcu_t& sm, uint8_t req, uint8_t coll, uint8_t en,
                     uint8_t u1, uint8_t u2, uint8_t u3, uint8_t tc,
                     uint8_t cts, uint8_t sr) {
        memset(&sm, 0, sizeof(sm));
        memcpy(sm.rom, rom_fill, sizeof(sm.rom));
        memcpy(sm.ram, ram_fill, sizeof(sm.ram));
        memcpy(sm.shared_ram, shared_fill, sizeof(sm.shared_ram));
        sm.pc = 0x1234; sm.a = 5; sm.x = 6; sm.y = 7; sm.s = 0x40;
        sm.sr = sr; sm.cts = cts;
        sm.device_mode[DEV_INT_REQUEST] = req;
        sm.device_mode[DEV_COLLISION] = coll;
        sm.device_mode[DEV_INT_ENABLE] = en;
        sm.device_mode[DEV_UART1_CTRL] = u1;
        sm.device_mode[DEV_UART2_CTRL] = u2;
        sm.device_mode[DEV_UART3_CTRL] = u3;
        sm.device_mode[DEV_TIMER_CTRL] = tc;
    };

    uint64_t checked = 0;
    std::vector<StubCall> la, lb, lc;

    auto drive = [&](uint8_t req, uint8_t coll, uint8_t en, uint8_t u1,
                     uint8_t u2, uint8_t u3, uint8_t tc, uint8_t cts,
                     uint8_t sr, const char* which) {
        reset(pat, req, coll, en, u1, u2, u3, tc, cts, sr);
        reset(ref, req, coll, en, u1, u2, u3, tc, cts, sr);
        reset(tst, req, coll, en, u1, u2, u3, tc, cts, sr);
        StubLog().clear(); SM_HandleInterrupt(pat);     la = StubLog();
        StubLog().clear(); Ref_SM_HandleInterrupt(ref); lb = StubLog();
        StubLog().clear(); GuardUnderTest(tst);         lc = StubLog();
        Check(pat, ref, tst, la, lb, lc, which);
        checked++;
    };

    /* Sweep 1: the guard's entire firing domain, exhaustively. INT_REQUEST is
     * zero (what the guard requires); everything else the ladder reads takes
     * every relevant value. */
    static const uint8_t kCtrl[] = { 0x00, 0x08, 0x10, 0x18 };
    static const uint8_t kTimer[] = { 0x00, 0x40, 0x80, 0xc0 };
    for (unsigned coll = 0; coll < 256; coll += 0x10)
        for (unsigned en = 0; en < 256; en += 0x11)
            for (uint8_t u1 : kCtrl) for (uint8_t u2 : kCtrl)
                for (uint8_t u3 : kCtrl) for (uint8_t tc : kTimer)
                    for (unsigned cts = 0; cts < 8; cts++)
                        for (unsigned sr = 0; sr <= 4; sr += 4)
                            drive(0, (uint8_t)coll, (uint8_t)en, u1, u2, u3,
                                  tc, (uint8_t)cts, (uint8_t)sr, "guard-domain");

    /* The collision byte again, every value, everything else pending-free. */
    for (unsigned coll = 0; coll < 256; coll++)
        for (unsigned sr = 0; sr <= 4; sr += 4)
            drive(0, (uint8_t)coll, 0xff, 0x18, 0x18, 0x18, 0xc0, 7,
                  (uint8_t)sr, "collision");

    /* Sweep 2: unconstrained random states, both guard halves exercised. */
    for (int i = 0; i < 4000000; i++)
    {
        uint32_t r = Rand(seed), r2 = Rand(seed), r3 = Rand(seed);
        drive((uint8_t)(r & 0x100 ? 0 : r), (uint8_t)(r >> 8),
              (uint8_t)(r >> 16), (uint8_t)(r >> 24), (uint8_t)r2,
              (uint8_t)(r2 >> 8), (uint8_t)(r2 >> 16), (uint8_t)(r2 >> 24),
              (uint8_t)(r3 & 4), "random");
    }

    printf("checked %llu states\n", (unsigned long long)checked);
    if (failures) { printf("FAIL: %d mismatches\n", failures); return 1; }
    printf("PASS\n");
    return 0;
}
