#!/usr/bin/env bash
#
# Differential check for the PCM patches (0008-0012).
#
#   ./patches/tests/pcm/run.sh
#
# Builds pcm.cpp twice — pristine and patched — into a driver that exercises
# PCM_Update with no ROMs and no MCU, and compares byte for byte. Each tick the
# driver digests the ENTIRE mutable PCM state (ram1, ram2, all 16 KiB of eram,
# every scalar), every sample handed to MCU_PostSample, and every interrupt
# raised; the last tick dumps that state raw.
#
# 44 cases over 10 modes: mk2 / mk1 / jv880, all 32 voices keyed on, all off,
# mixed key and register traffic, reg_slots of 1, 12, 28 and 32, and two
# wide-pitch modes that drive sub_phase_of across its full 0..4 range. Those
# last two matter: the stock modes only reach 0..1, so without them patch 0012's
# skipped fourth address step would never be exercised.
#
# Then it rebuilds with a deliberate bug — one flipped tv_counter bit test in
# calc_tv's tap ladder — and checks the harness rejects it.
#
# Needs no ROMs.
set -eu
cd "$(dirname "$0")"
REPO=$(cd ../../.. && pwd)
CORE="${NUKED_DIR:-$REPO/vendor/nuked-sc55}"

if [ ! -e "$CORE/src/backend/pcm.cpp" ]; then
    echo "error: no core checkout at $CORE" >&2
    echo "       run: git submodule update --init --recursive" >&2
    exit 1
fi

WORK=$(mktemp -d); trap 'rm -rf "$WORK"' EXIT
cp -a "$CORE/src" "$WORK/src"

# config.h is generated by the build; the driver only needs it to exist.
mkdir -p "$WORK/gen/backend"
sed -e 's/#cmakedefine01 \(.*\)/#define \1 0/' \
    -e 's/@[A-Z_]*@/0/g' "$CORE/src/backend/config.h.in" > "$WORK/gen/backend/config.h"

build() { # <pcm.cpp> <out>
    g++ -O2 -g -std=c++20 -I"$WORK/src/backend" -I"$WORK/gen/backend" \
        -o "$2" "$1" h/driver.cpp -Ih
}

build "$WORK/src/backend/pcm.cpp" "$WORK/drv-ref"

mkdir -p "$WORK/patched"
cp -a "$WORK/src" "$WORK/patched/src"
applied=0
for p in "$REPO"/patches/00{08,09,10,11,12}-*.patch; do
    [ -e "$p" ] || { echo "error: missing $p" >&2; exit 1; }
    if ! (cd "$WORK/patched" && patch -p1 --quiet --forward -i "$p"); then
        echo "error: $(basename "$p") did not apply — the core has moved" >&2
        exit 1
    fi
    applied=$((applied + 1))
done
if [ "$applied" -ne 5 ]; then
    echo "error: applied $applied patches, expected 5" >&2
    exit 1
fi
# A comparison against an unmodified candidate would pass trivially.
if cmp -s "$WORK/src/backend/pcm.cpp" "$WORK/patched/src/backend/pcm.cpp"; then
    echo "error: the patched pcm.cpp is identical to the pristine one" >&2
    exit 1
fi
build "$WORK/patched/src/backend/pcm.cpp" "$WORK/drv-cand"

run_cases() { # <cand> <ref>  -> prints PASS/FAIL
    local fails=0
    for mode in 0 1 2 3 4 5 6 7 8 9; do
        for seed in 1 12345 777777 424242; do
            a=$(PCM_TICKS=6000 "$2" "$mode" "$seed" | md5sum)
            b=$(PCM_TICKS=6000 "$1" "$mode" "$seed" | md5sum)
            [ "$a" = "$b" ] || fails=$((fails + 1))
        done
    done
    for mode in 0 2; do
        for seed in 5 6; do
            a=$(PCM_TERSE=1 PCM_TICKS=40000 "$2" "$mode" "$seed" | md5sum)
            b=$(PCM_TERSE=1 PCM_TICKS=40000 "$1" "$mode" "$seed" | md5sum)
            [ "$a" = "$b" ] || fails=$((fails + 1))
        done
    done
    echo "$fails"
}

fails=$(run_cases "$WORK/drv-cand" "$WORK/drv-ref")
if [ "$fails" = "0" ]; then
    echo "PASS: 44 cases identical to the unpatched core"
else
    echo "FAIL: $fails of 44 cases differ"; exit 1
fi

# The harness must be capable of failing.
build broken1.cpp "$WORK/drv-broken" 2>/dev/null || {
    echo "note: could not build the deliberate-bug variant, skipping that check"; exit 0; }
fails=$(run_cases "$WORK/drv-broken" "$WORK/drv-ref")
if [ "$fails" = "0" ]; then
    echo "FAIL: the harness did not reject a deliberately broken build"; exit 1
fi
echo "ok:   rejects a deliberately broken build ($fails of 44 cases)"
